version: 2.1
orbs:
  node: circleci/node@3.0.0
defaults: &defaults
  docker: 
      - image: circleci/node:13.8.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_packages"
          paths: 
            - /src/node_pkg
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "npm_packages"
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit
workflows:
  node-tests:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyze:
          requires: 
            - test
